"""Plain-text report assembly from pipeline stage outputs.

Python port of render_txt.R. Reads a working directory containing stage
outputs and metadata.json, returns a single plain-text review as a string.

The caller decides what to do with the text (write to disk, stream, etc.).
"""

from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path
from textwrap import fill

# ---------------------------------------------------------------------------
# Report chrome — customize for your fork or deployment.
# ---------------------------------------------------------------------------

HEADER_TITLE = "CRITICAL PEER REVIEW"
TOOL_NAME = "presubmit"
FOOTER_URL = "https://github.com/scdenney/presubmit"

DISCLAIMER = (
    "This report was generated by an automated peer-review pipeline that uses "
    "large language models. No human editor reviewed it. Any claims made in "
    "it should be verified by a qualified expert."
)

PLATO_QUOTE = (
    "I am wiser than this person; for it is likely that neither of us knows "
    "anything fine and good, but he thinks he knows something when he does "
    "not know it, whereas I, just as I do not know, do not think I know, "
    "either. I seem, then, to be wiser than him in this small way, at least: "
    "that what I do not know, I do not think I know, either."
)
PLATO_ATTRIBUTION = "Plato, The Apology of Socrates, 21d"

POPPER_QUOTE = (
    "To err is human. All human knowledge is fallible and therefore "
    "uncertain. It follows that we must distinguish sharply between truth "
    "and certainty. That to err is human means not only that we must "
    "constantly struggle against error, but also that, even when we have "
    "taken the greatest care, we cannot be completely certain that we have "
    "not made a mistake."
)
POPPER_ATTRIBUTION = "Karl Popper, 'Knowledge and the Shaping of Reality'"

WIDTH = 72
QUOTE_WIDTH = 68


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_text(work_dir: str | Path) -> str:
    """Assemble a plain-text review from stage outputs in `work_dir`.

    Expects `work_dir` to contain at minimum a `metadata.json` and
    `10_latex_body.txt`. Optional inputs: `08b_polisher.txt` (editor's note
    fallback), `09b_proofread_clean.txt`, `09c_copyedit.txt`.
    """
    work_dir = Path(work_dir)
    metadata = _read_metadata(work_dir)

    title = metadata.get("title") or "Untitled"
    authors = metadata.get("authors") or "Unknown Authors"
    year = metadata.get("year") or str(date.today().year)
    editor_note = _resolve_editor_note(metadata, work_dir)
    body = _read_body(work_dir)
    copyedit = _read_optional(work_dir / "09c_copyedit.txt")
    proofread = _read_optional(work_dir / "09b_proofread_clean.txt")
    if "=NULL=" in proofread:
        proofread = ""

    return _assemble(
        title=title,
        authors=authors,
        year=year,
        citation=metadata.get("citation", ""),
        url=metadata.get("url", ""),
        abstract_summary=metadata.get("abstract_summary", ""),
        key_methodology=metadata.get("key_methodology", ""),
        research_question=metadata.get("research_question", ""),
        editor_note=editor_note,
        body=body,
        copyedit=copyedit,
        proofread=proofread,
    )


# ---------------------------------------------------------------------------
# Readers
# ---------------------------------------------------------------------------


def _read_metadata(work_dir: Path) -> dict:
    path = work_dir / "metadata.json"
    if not path.exists():
        raise FileNotFoundError(f"metadata.json not found in {work_dir}")
    return json.loads(path.read_text(encoding="utf-8"))


def _read_optional(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def _read_body(work_dir: Path) -> str:
    raw = _read_optional(work_dir / "10_latex_body.txt")
    return _clean_body(raw) if raw else ""


def _resolve_editor_note(metadata: dict, work_dir: Path) -> str:
    note = (metadata.get("editor_note") or "").strip()
    if len(note) >= 5:
        return _strip_markdown(note)
    fallback = _read_optional(work_dir / "08b_polisher.txt")
    return _strip_markdown(fallback) if fallback else ""


# ---------------------------------------------------------------------------
# Cleaners
# ---------------------------------------------------------------------------


_LATEX_SUBS = [
    (re.compile(r"\\clearpage"), "\n\n---\n\n"),
    (re.compile(r"\\section\*?\{([^}]*)\}"), r"\n\1\n"),
    (re.compile(r"\\subsection\*?\{([^}]*)\}"), r"\n\1\n"),
    (re.compile(r"\\textbf\{([^}]*)\}"), r"\1"),
    (re.compile(r"\\textit\{([^}]*)\}"), r"\1"),
    (re.compile(r"\\href\{[^}]*\}\{([^}]*)\}"), r"\1"),
    (re.compile(r"\\url\{([^}]*)\}"), r"[\1]"),
    (re.compile(r"\\\\"), "\n"),
    (re.compile(r"\\[a-zA-Z]+\*?\{[^}]*\}"), ""),
    (re.compile(r"\\[a-zA-Z]+\*?"), ""),
    (re.compile(r"[ \t]+\n"), "\n"),
    (re.compile(r"\n{3,}"), "\n\n"),
]


def _strip_latex(text: str) -> str:
    for pattern, replacement in _LATEX_SUBS:
        text = pattern.sub(replacement, text)
    return text.strip()


_SECTION_HEADERS = [
    (re.compile(r"##\s*\**Is It Credible\?\**\s*", re.IGNORECASE), "SUMMARY", "Is It Credible?\n"),
    (re.compile(r"##\s*\**Data Editor\**\s*", re.IGNORECASE), "DATA EDITOR", ""),
    (re.compile(r"##\s*\**Potential Issues\**\s*", re.IGNORECASE), "POTENTIAL ISSUES", ""),
    (re.compile(r"##\s*\**Future Research\**\s*", re.IGNORECASE), "FUTURE RESEARCH", ""),
]


def _strip_markdown(text: str) -> str:
    for pattern, label, suffix in _SECTION_HEADERS:
        replacement = f"{_divider()}\n{label}\n{_divider()}\n\n{suffix}"
        text = pattern.sub(replacement, text)

    text = re.sub(r"^###?\s+(.+)$", r"\n\1\n", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


_HAS_DATA_EDITOR = re.compile(r"##\s*\**Data Editor\**", re.IGNORECASE)
_HAS_FUTURE_RESEARCH = re.compile(r"##\s*\**Future Research\**", re.IGNORECASE)
_HAS_IS_IT_CREDIBLE = re.compile(r"##\s*\**Is It Credible", re.IGNORECASE)
_HAS_SUMMARY = re.compile(r"##\s*\**Summary", re.IGNORECASE)


def _clean_body(raw: str) -> str:
    if _HAS_DATA_EDITOR.search(raw) and _HAS_FUTURE_RESEARCH.search(raw):
        raw = _reorder_data_editor_after_future_research(raw)

    if re.search(r"\\section|\\subsection|\\textbf", raw):
        raw = _strip_latex(raw)

    has_headers = (
        _HAS_IS_IT_CREDIBLE.search(raw)
        or _HAS_SUMMARY.search(raw)
        or _HAS_DATA_EDITOR.search(raw)
    )
    cleaned = _strip_markdown(raw)
    return cleaned if has_headers else _section("Review Report", cleaned)


def _reorder_data_editor_after_future_research(text: str) -> str:
    """Move the Data Editor block so it appears after Future Research."""
    sections = re.split(r"\n(?=## )|\n(?=# )", text)

    de_idx = next((i for i, s in enumerate(sections) if _HAS_DATA_EDITOR.search(s)), None)
    fr_idx = next((i for i, s in enumerate(sections) if _HAS_FUTURE_RESEARCH.search(s)), None)

    if de_idx is None or fr_idx is None or de_idx >= fr_idx:
        return text

    de_block = sections.pop(de_idx)
    fr_idx = next((i for i, s in enumerate(sections) if _HAS_FUTURE_RESEARCH.search(s)), None)
    if fr_idx is None or fr_idx == len(sections) - 1:
        sections.append(de_block)
    else:
        sections.insert(fr_idx + 1, de_block)
    return "\n".join(sections)


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------


def _divider() -> str:
    return "=" * WIDTH


def _thin_divider() -> str:
    return "-" * WIDTH


def _section(title: str, content: str) -> str:
    content = content.strip()
    if not content:
        return ""
    return f"{_divider()}\n{title.upper()}\n{_divider()}\n\n{content}\n\n"


def _format_quote(body: str, attribution: str) -> str:
    wrapped = fill(body, width=QUOTE_WIDTH)
    pad = max(0, QUOTE_WIDTH - len(attribution))
    return f"{wrapped}\n\n{' ' * pad}{attribution}"


def _header(title: str, authors: str, year: str) -> str:
    today = date.today().strftime("%B %d, %Y")
    return "\n".join([
        _divider(),
        HEADER_TITLE,
        _thin_divider(),
        f'A Report on "{title}"',
        f"by {authors} ({year})",
        "",
        f"{TOOL_NAME}  |  {today}",
        _divider(),
    ])


def _overview(
    citation: str,
    url: str,
    abstract_summary: str,
    key_methodology: str,
    research_question: str,
) -> str:
    lines = []
    if citation.strip():
        lines.append(f"Citation:          {citation}")
    if url.strip() and "not available" not in url.lower():
        lines.append(f"URL:               {url}")
    if abstract_summary.strip():
        lines.append(f"Abstract Summary:  {abstract_summary}")
    if key_methodology.strip():
        lines.append(f"Key Methodology:   {key_methodology}")
    if research_question.strip():
        lines.append(f"Research Question: {research_question}")
    return "\n".join(lines)


def _footer() -> str:
    return "\n".join([
        _divider(),
        f"Generated by {TOOL_NAME}.",
        FOOTER_URL,
        _divider(),
    ])


def _assemble(
    *,
    title: str,
    authors: str,
    year: str,
    citation: str,
    url: str,
    abstract_summary: str,
    key_methodology: str,
    research_question: str,
    editor_note: str,
    body: str,
    copyedit: str,
    proofread: str,
) -> str:
    header = _header(title, authors, year)
    disclaimer_block = _section("Disclaimer", DISCLAIMER)

    quotes = "\n\n\n".join([
        _format_quote(PLATO_QUOTE, PLATO_ATTRIBUTION),
        _format_quote(POPPER_QUOTE, POPPER_ATTRIBUTION),
    ])

    overview_block = _section(
        "Overview",
        _overview(citation, url, abstract_summary, key_methodology, research_question),
    )

    editor_section = _section("Editor's Note", editor_note)
    copyedit_section = _section("Copyediting", copyedit)
    proofread_section = _section("Proofreading", proofread)

    # BEGIN REVIEW / END REVIEW sentinels bracket the LLM-generated content.
    # Preserved so downstream hashing, diffing, or stripping tools have a
    # stable boundary regardless of header chrome.
    review_parts = [
        p.rstrip() for p in (editor_section, body, copyedit_section, proofread_section)
        if p.strip()
    ]
    review_body = "\n\n".join(review_parts)
    review_block = f"BEGIN REVIEW\n\n{review_body}\n\nEND REVIEW"

    blocks = [header, disclaimer_block, quotes, overview_block, review_block, _footer()]
    blocks = [b.rstrip() for b in blocks if b.strip()]
    return "\n\n".join(blocks) + "\n"
